/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows --types chevreuse-test.glb 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { RigidBody } from "@react-three/rapier";
import { useLoader } from "@react-three/fiber";
import { TextureLoader, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial008_1: THREE.Mesh;
    defaultMaterial007_1: THREE.Mesh;
    defaultMaterial009_1: THREE.Mesh;
    defaultMaterial001_1: THREE.Mesh;
    defaultMaterial001_2: THREE.Mesh;
    defaultMaterial001_3: THREE.Mesh;
    defaultMaterial001_4: THREE.Mesh;
    defaultMaterial001_5: THREE.Mesh;
    defaultMaterial001_6: THREE.Mesh;
    defaultMaterial001_7: THREE.Mesh;
    defaultMaterial008_2: THREE.Mesh;
    defaultMaterial007_2: THREE.Mesh;
    defaultMaterial008_3: THREE.Mesh;
    defaultMaterial007_3: THREE.Mesh;
    defaultMaterial008_4: THREE.Mesh;
    defaultMaterial007_4: THREE.Mesh;
    defaultMaterial001_8: THREE.Mesh;
    defaultMaterial001_9: THREE.Mesh;
    defaultMaterial001_10: THREE.Mesh;
    defaultMaterial001_11: THREE.Mesh;
    defaultMaterial001_12: THREE.Mesh;
    defaultMaterial001_13: THREE.Mesh;
    defaultMaterial001_14: THREE.Mesh;
    defaultMaterial001_15: THREE.Mesh;
    defaultMaterial001_16: THREE.Mesh;
    defaultMaterial001_17: THREE.Mesh;
    defaultMaterial009_2: THREE.Mesh;
    defaultMaterial009_3: THREE.Mesh;
    defaultMaterial009_4: THREE.Mesh;
    defaultMaterial009_5: THREE.Mesh;
    defaultMaterial009_6: THREE.Mesh;
    defaultMaterial001_18: THREE.Mesh;
    defaultMaterial001_19: THREE.Mesh;
    defaultMaterial001_20: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
    Cylinder_3: THREE.Mesh;
    Cylinder_4: THREE.Mesh;
    Cylinder_5: THREE.Mesh;
    Cylinder_6: THREE.Mesh;
    Cylinder_7: THREE.Mesh;
    Cylinder_8: THREE.Mesh;
    Cylinder_9: THREE.Mesh;
    Cylinder_10: THREE.Mesh;
    Cylinder_11: THREE.Mesh;
    Cylinder_12: THREE.Mesh;
    Cylinder_13: THREE.Mesh;
    ["pylon(Clone)_1"]: THREE.Mesh;
    Cube_1: THREE.Mesh;
    Cube_2: THREE.Mesh;
    Cube001_1: THREE.Mesh;
    Cube001_2: THREE.Mesh;
    Plane_1: THREE.Mesh;
    Plane_2: THREE.Mesh;
    Plane_3: THREE.Mesh;
    Plane001: THREE.Mesh;
    defaultMaterial008: THREE.Mesh;
    defaultMaterial007: THREE.Mesh;
    defaultMaterial001: THREE.Mesh;
    defaultMaterial002: THREE.Mesh;
    defaultMaterial009: THREE.Mesh;
    Cylinder: THREE.Mesh;
    ["pylon(Clone)"]: THREE.Mesh;
  };
  materials: {
    DefaultMaterial: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    pylon: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function ChevreuseTest(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/chevreuse-test.glb") as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
      scale={140}
      position={[0, 112, 0]}
      rotation={[0, (-Math.PI / 2) * 0.88, 0]}
    >
      <group
        position={[0.455, -0.539, -0.512]}
        rotation={[-0.829, 0.018, 0.086]}
        scale={0.733}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial008_1.geometry}
          material={materials.DefaultMaterial}
          position={[0.852, -0.771, 0.218]}
          rotation={[-0.017, 0, 0.049]}
          scale={0.291}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_1.geometry}
          material={materials.DefaultMaterial}
          position={[1.019, -0.763, 0.247]}
          rotation={[-0.579, -0.012, 0.115]}
          scale={0.543}
        />
      </group>
      <group
        position={[4.284, -0.351, 2.671]}
        rotation={[-3.079, 1.235, 3.052]}
        scale={0.434}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial009_1.geometry}
          material={materials.DefaultMaterial}
          position={[5.289, -0.527, 0.167]}
          rotation={[-0.03, 0, -0.002]}
          scale={0.22}
        />
      </group>
      <group position={[-3.412, -0.363, 0.032]} rotation={[-0.019, 0, 0.045]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_1.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[-1.008, -0.159, 4.715]}
        rotation={[-0.088, 0.991, 0.081]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_2.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[-0.751, -0.421, 0.271]}
        rotation={[-0.04, 0.227, 0.038]}
        scale={0.648}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_3.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[1.536, -0.259, 2.986]}
        rotation={[-0.14, 1.247, 0.117]}
        scale={0.648}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_4.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[1.07, -0.278, 2.698]}
        rotation={[-0.105, 1.108, 0.083]}
        scale={0.648}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_5.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[3.69, -0.173, 3.18]}
        rotation={[-3.044, 1.296, 3.01]}
        scale={0.648}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_6.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[4.437, -0.155, 3.037]}
        rotation={[-3.105, 1.059, 3.068]}
        scale={0.648}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_7.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[2.043, -0.313, -0.154]}
        rotation={[-0.025, 0.003, 0.041]}
        scale={0.538}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial008_2.geometry}
          material={materials.DefaultMaterial}
          position={[0.852, -0.771, 0.218]}
          rotation={[-0.017, 0, 0.049]}
          scale={0.291}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_2.geometry}
          material={materials.DefaultMaterial}
          position={[1.019, -0.763, 0.247]}
          rotation={[-0.579, -0.012, 0.115]}
          scale={0.543}
        />
      </group>
      <group
        position={[2.305, -0.313, 0.454]}
        rotation={[-0.093, 1.301, 0.131]}
        scale={0.538}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial008_3.geometry}
          material={materials.DefaultMaterial}
          position={[0.852, -0.771, 0.218]}
          rotation={[-0.017, 0, 0.049]}
          scale={0.291}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_3.geometry}
          material={materials.DefaultMaterial}
          position={[1.019, -0.763, 0.247]}
          rotation={[-0.579, -0.012, 0.115]}
          scale={0.543}
        />
      </group>
      <group
        position={[3.12, -0.256, 0.405]}
        rotation={[-0.02, 0.003, 0.03]}
        scale={0.538}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial008_4.geometry}
          material={materials.DefaultMaterial}
          position={[0.852, -0.771, 0.218]}
          rotation={[-0.017, 0, 0.049]}
          scale={0.291}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_4.geometry}
          material={materials.DefaultMaterial}
          position={[1.019, -0.763, 0.247]}
          rotation={[-0.579, -0.012, 0.115]}
          scale={0.543}
        />
      </group>
      <group position={[-0.023, -0.062, -1.098]} rotation={[-0.042, 0, -0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_8.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[7.257, -0.125, -6.373]}
        rotation={[-3.008, -1.211, -3.013]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_9.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group position={[6.012, -0.329, 3.964]} rotation={[3.05, 1.349, -3.009]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_10.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[4.976, -0.477, -8.036]}
        rotation={[0.004, -1.203, 0.059]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_11.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[4.562, -0.491, -8.779]}
        rotation={[-0.098, -1.203, -0.042]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_12.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[11.325, -0.495, -1.288]}
        rotation={[-3.101, 0.391, -3.108]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_13.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group position={[3.791, -0.498, -8.4]} rotation={[-0.07, -1.008, -0.01]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_14.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group position={[12.017, -0.296, -3.12]} rotation={[3.08, 0.07, -3.122]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_15.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[2.395, 0.069, -0.132]}
        rotation={[-0.043, 0.745, -0.025]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_16.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[11.951, -0.325, -3.937]}
        rotation={[3.085, -0.126, -3.125]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_17.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[8.03, -0.029, 0.886]}
        rotation={[3.021, 1.236, -3.079]}
        scale={1.031}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial009_2.geometry}
          material={materials.DefaultMaterial}
          position={[5.289, -0.527, 0.167]}
          rotation={[-0.03, 0, -0.002]}
          scale={0.22}
        />
      </group>
      <group
        position={[20.108, 12.525, -14.125]}
        rotation={[-2.244, -0.956, -3.09]}
        scale={3.86}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial009_3.geometry}
          material={materials.DefaultMaterial}
          position={[5.289, -0.527, 0.167]}
          rotation={[-0.03, 0, -0.002]}
          scale={0.22}
        />
      </group>
      <group
        position={[20.036, -0.336, -21.597]}
        rotation={[3.125, -0.987, -3.085]}
        scale={3.86}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial009_4.geometry}
          material={materials.DefaultMaterial}
          position={[5.289, -0.527, 0.167]}
          rotation={[-0.03, 0, -0.002]}
          scale={0.22}
        />
      </group>
      <group
        position={[19.815, -4.646, -21.307]}
        rotation={[1.809, -0.612, 2.42]}
        scale={3.86}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial009_5.geometry}
          material={materials.DefaultMaterial}
          position={[5.289, -0.527, 0.167]}
          rotation={[-0.03, 0, -0.002]}
          scale={0.22}
        />
      </group>
      <group
        position={[20.443, -0.348, -21.408]}
        rotation={[3.126, -0.987, -3.084]}
        scale={3.86}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial009_6.geometry}
          material={materials.DefaultMaterial}
          position={[5.289, -0.527, 0.167]}
          rotation={[-0.03, 0, -0.002]}
          scale={0.22}
        />
      </group>
      <group
        position={[6.256, -0.638, -10.862]}
        rotation={[-0.137, -1.202, -0.084]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_18.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[6.321, -0.625, -12.406]}
        rotation={[-0.122, -1.202, -0.086]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_19.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[7.01, -0.708, -13.566]}
        rotation={[-0.134, -1.202, -0.095]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001_20.geometry}
          material={materials.DefaultMaterial}
          position={[5.467, -0.605, 0.278]}
          rotation={[-0.028, 0, -0.004]}
          scale={0.173}
        />
      </group>
      <group
        position={[0.244, 0.754, -0.069]}
        rotation={[-0.156, 0.047, -0.247]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials["Material.004"]}
          position={[3.283, -0.658, 0.219]}
          rotation={[1.51, -0.019, 2.527]}
          scale={[0.008, 0.076, 0.008]}
        />
      </group>
      <group
        position={[0.101, 0.476, 0.169]}
        rotation={[-0.086, 0.077, -0.148]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2.geometry}
          material={materials["Material.004"]}
          position={[3.283, -0.658, 0.219]}
          rotation={[1.51, -0.019, 2.527]}
          scale={[0.008, 0.076, 0.008]}
        />
      </group>
      <group position={[0.18, -0.001, 1.559]} rotation={[0, 0.468, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_3.geometry}
          material={materials["Material.004"]}
          position={[3.283, -0.658, 0.219]}
          rotation={[1.51, -0.019, 2.527]}
          scale={[0.008, 0.076, 0.008]}
        />
      </group>
      <group position={[-0.065, -0.001, 0.764]} rotation={[0, 0.205, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_4.geometry}
          material={materials["Material.004"]}
          position={[3.283, -0.658, 0.219]}
          rotation={[1.51, -0.019, 2.527]}
          scale={[0.008, 0.076, 0.008]}
        />
      </group>
      <group
        position={[0.182, 0.578, 0.121]}
        rotation={[-0.105, 0.084, -0.181]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_5.geometry}
          material={materials["Material.004"]}
          position={[3.283, -0.658, 0.219]}
          rotation={[1.51, -0.019, 2.527]}
          scale={[0.008, 0.076, 0.008]}
        />
      </group>
      <group
        position={[-0.061, -0.338, 0.008]}
        rotation={[0.072, -0.008, 0.112]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_6.geometry}
          material={materials["Material.004"]}
          position={[3.283, -0.658, 0.219]}
          rotation={[1.51, -0.019, 2.527]}
          scale={[0.008, 0.076, 0.008]}
        />
      </group>
      <group position={[0.1, 0.488, 0.169]} rotation={[-0.085, 0.077, -0.147]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_7.geometry}
          material={materials["Material.004"]}
          position={[3.283, -0.658, 0.219]}
          rotation={[1.51, -0.019, 2.527]}
          scale={[0.008, 0.076, 0.008]}
        />
      </group>
      <group position={[0.009, 0.013, 0.169]} rotation={[0.001, 0.055, 0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_8.geometry}
          material={materials["Material.004"]}
          position={[3.283, -0.658, 0.219]}
          rotation={[1.51, -0.019, 2.527]}
          scale={[0.008, 0.076, 0.008]}
        />
      </group>
      <group
        position={[0.127, 0.513, -0.023]}
        rotation={[-0.099, 0.025, -0.155]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_9.geometry}
          material={materials["Material.004"]}
          position={[3.283, -0.658, 0.219]}
          rotation={[1.51, -0.019, 2.527]}
          scale={[0.008, 0.076, 0.008]}
        />
      </group>
      <group position={[-0.09, -0.823, 0.147]} rotation={[0.155, 0.047, 0.261]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_10.geometry}
          material={materials["Material.004"]}
          position={[3.283, -0.658, 0.219]}
          rotation={[1.51, -0.019, 2.527]}
          scale={[0.008, 0.076, 0.008]}
        />
      </group>
      <group position={[0.048, 0.201, 0.163]} rotation={[-0.03, 0.061, -0.052]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_11.geometry}
          material={materials["Material.004"]}
          position={[3.283, -0.658, 0.219]}
          rotation={[1.51, -0.019, 2.527]}
          scale={[0.008, 0.076, 0.008]}
        />
      </group>
      <group
        position={[-0.039, -0.238, 0.003]}
        rotation={[0.056, -0.007, 0.086]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_12.geometry}
          material={materials["Material.004"]}
          position={[3.283, -0.658, 0.219]}
          rotation={[1.51, -0.019, 2.527]}
          scale={[0.008, 0.076, 0.008]}
        />
      </group>
      <group position={[0, 0.017, -0.002]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_13.geometry}
          material={materials["Material.004"]}
          position={[3.283, -0.658, 0.219]}
          rotation={[1.51, -0.019, 2.527]}
          scale={[0.008, 0.076, 0.008]}
        />
      </group>
      <group position={[-0.005, 0.007, 0.074]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pylon(Clone)_1"].geometry}
          material={materials.pylon}
          position={[0.635, -0.778, 0.03]}
          rotation={[-0.012, 0.071, 0.049]}
          scale={0.074}
        />
      </group>
      <group
        position={[0.254, -0.788, 0.064]}
        rotation={[0, -0.13, 0]}
        scale={0.01}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[0, 0.005, 0]}>
      <mesh layers={1} geometry={nodes.Plane_1.geometry}>
          <meshBasicMaterial color={"#ffffff"} depthTest={false} depthWrite={false} fog={false} />
        </mesh>

        <mesh layers={1} geometry={nodes.Plane_2.geometry}>
          <meshBasicMaterial color={"#ffffff"} depthTest={false} depthWrite={false} fog={false} />
        </mesh>

        <mesh layers={1} geometry={nodes.Plane_3.geometry}>
          <meshBasicMaterial color={"#ffffff"} depthTest={false} depthWrite={false} fog={false} />
        </mesh>
      </group>
      <RigidBody type="fixed" colliders="trimesh" position={[0, 0.005, 0]}>
        <>
          <group
            position={[9.022, -1.161, -8.889]}
            rotation={[-1.472, -1.524, -1.427]}
            scale={0.01}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_1.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_2.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group position={[0, 0.001, 0]}>
            <mesh
              receiveShadow
              geometry={nodes.Plane_1.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              receiveShadow
              geometry={nodes.Plane_2.geometry}
              material={materials["Material.002"]}
              position={[0, 0.0001, 0]}
            />
            <mesh
              receiveShadow
              geometry={nodes.Plane_3.geometry}
              material={materials["Material.003"]}
            />
          </group>
        </>
      </RigidBody>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material.007"]}
        position={[8.591, -0.459, -5.771]}
        scale={8.953}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial008.geometry}
        material={materials.DefaultMaterial}
        position={[0.852, -0.771, 0.218]}
        rotation={[-0.017, 0, 0.049]}
        scale={0.291}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial007.geometry}
        material={materials.DefaultMaterial}
        position={[1.019, -0.763, 0.247]}
        rotation={[-0.579, -0.012, 0.115]}
        scale={0.543}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial001.geometry}
        material={materials.DefaultMaterial}
        position={[5.467, -0.605, 0.278]}
        rotation={[-0.028, 0, -0.004]}
        scale={0.173}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial002.geometry}
        material={materials.DefaultMaterial}
        position={[5.314, -0.605, 0.33]}
        rotation={[-3.113, 0.449, 3.127]}
        scale={0.441}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial009.geometry}
        material={materials.DefaultMaterial}
        position={[5.289, -0.527, 0.167]}
        rotation={[-0.03, 0, -0.002]}
        scale={0.22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.004"]}
        position={[3.283, -0.658, 0.219]}
        rotation={[1.51, -0.019, 2.527]}
        scale={[0.008, 0.076, 0.008]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["pylon(Clone)"].geometry}
        material={materials.pylon}
        position={[0.635, -0.778, 0.03]}
        rotation={[-0.012, 0.071, 0.049]}
        scale={0.074}
      />
    </group>
  );
}

useGLTF.preload("/chevreuse-test.glb");
